spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/nicstop_db
        username: murro
        password: deadcat
        driver-class-name: org.postgresql.Driver
    mvc:
        favicon: enabled
        
    jpa:
        hibernate:
            ddl-auto: create-drop
        database: postgresql
        show-sql: false
        properties:
            hibernate:
                format_sql: false
