spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/nicstop_db
        username: ${PSQL_USERNAME}
        password: ${PSQL_PASSWORD}
        driver-class-name: org.postgresql.Driver
    mvc:
        favicon: enabled
        
    jpa:
        hibernate:
            ddl-auto: create
        database: postgresql
        show-sql: false
        properties:
            hibernate:
                format_sql: false
server:
    address: 0.0.0.0
